### PR TITLE
Create Pete - Done

### PR DESCRIPTION
**Pull request by Camp91783**

### CODE REVIEW

**Comment by andrewek** [comment]
@Camp91783 Your answers are correct. In the future, though, rather than creating a new file for this, just modify the file that's already there (`lib/conditionals.md`, in this case). That might make your life a little simpler.

**Comment by Camp91783** [comment]
Will do.  Sorry about that, still trying to get Github all figured out and been tough with moving this week.  Will make sure I do it properly for the rest due Monday.

Peter

**Comment by andrewek** [comment]
It's alright. Drop a line if you run into any issues. Hopefully the move went / is going well!

**Comment by Camp91783** [comment]
Andrew,
 Im finishing up the rest of my prompts today and will have them submitted
by tonight.  The exercises I am still working on.  My girlfriend had her
grandma die on Friday so have been trying to wrap up all my moving to
prepare for Lincoln in a couple weeks and now getting everything ready to
head out to the Bay area for the funeral.  I'm hoping to have them
submitted tonight or tomorrow but need to make sure Im getting this all
down correctly.  I am going to be traveling all day Wednesday so will be
able to get tons done while in airports all day.  I'm hoping that I should
have everything all in and started next weeks assignments by Wednesday
evening.  I'll be in California until next week at some point but will have
plenty of free time to make sure I am not only all caught up but should be
ahead.  If this doesn't work I'll do what I need to do to get it submitted
by midnight tonight.  I do not want to jeopardize my spot in the class at
all.  Moving took much longer than I had anticipated and then had this
other situation come up.  Sorry again for the inconvenience.

Peter Camp

**Pull request closed without merging**
